version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    build:
      context: prometheus/
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - "monitoring-network"

  grafana:
    build:
      context: grafana/
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - "monitoring-network"
    depends_on:
      - prometheus

  alertmanager:
    build:
      context: alertmanager/
    container_name: alertmanager
    ports:
      - 9093:9093
    networks:
      - "monitoring-network"

networks:
  monitoring-network:
    driver: bridge
