FROM prom/prometheus

COPY ./config/prometheus.yml /etc/prometheus/prometheus.yml
COPY ./config/alert.rules /etc/prometheus/alert.rules
COPY ./config/blackbox_targets.yml /etc/prometheus/blackbox_targets.yml
